modLoader="javafml" #mandatory
loaderVersion = "[2,)" #mandatory
license = "MIT"
[[mods]] #mandatory
modId = "test_star_tp" #mandatory
version = "1.0.2" #mandatory
displayName = "Test Star Mod" #mandatory
authors = "lyuxc" #optional
description = '''a mod for modpack'''

[[dependencies.test_star_multiblock]] #optional
modId="neoforge" #mandatory
type="required"
versionRange = "[20.6.7-beta,)" #mandatory
ordering="NONE"
side="BOTH"

